_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.11
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
action_repeat:
    value: 4
batch_size:
    value: 32
buffer_capacity:
    value: 1000
clip_param:
    value: 0.2
device:
    value: cuda:0
gamma:
    value: 0.99
max_episodes:
    value: 2000
ppo_epoch:
    value: 10
