_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 1
                - 2
                - 13
                - 16
                - 55
            "4": 3.10.12
            "5": 0.20.1
            "8":
                - 1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 128
data_augmentation:
    value:
        - RandomRotation
        - RandomAffine
device:
    value: cuda
early_stopping_metric:
    value: accuracy
early_stopping_patience:
    value: 7
learning_rate:
    value: 0.001
log_every_epoch:
    value: true
logging_steps:
    value: 100
loss_fn:
    value: CrossEntropyLoss()
maximize_metric:
    value: true
num_epochs:
    value: 20
num_workers:
    value: 2
optimizer_type:
    value: Adam
output_dir:
    value: models/
pin_memory:
    value: true
seed:
    value: 42
use_early_stopping:
    value: true
use_wandb:
    value: true
validation_split:
    value: 0.1
wandb_project:
    value: dl-lab1-knowledge-distillation
weight_decay:
    value: 0.0001
